### ISSUE TITLE
### Checklist

### ISSUE THREAD

**Issue by kirmo9** [kirmo9/06funks.enact-icloud.com#3]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [x] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version 

### Description

![image](https://user-images.githubusercontent.com/20538090/177404139-4f113bba-e808-477f-9055-e0b46f53e5fd.png)
app.me returns my user id (int) It doesn't work because it is specified as app.me.is_premium in the code

There are other errors due to this reason.
like this
![image](https://user-images.githubusercontent.com/20538090/177407911-c364b5cf-2c76-4fa9-a150-857a63e81523.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/20538090/177404139-4f113bba-e808-477f-9055-e0b46f53e5fd.png)

### Logs

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
    app.run(main())
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pyrogram\methods\utilities\run.py", line 77, in run
    run(coroutine)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\USER\Desktop\userbott\main.py", line 123, in main
    await app.send_document("me", __file__, caption=f"{now_str_date()} - Userbot start")
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pyrogram\methods\messages\send_document.py", line 161, in send_document
    file = await self.save_file(document, progress=progress, progress_args=progress_args)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\pyrogram\methods\advanced\save_file.py", line 128, in save_file
    file_size_limit_mib = 4000 if self.me.is_premium else 2000
AttributeError: 'int' object has no attribute 'is_premium'
```

_Originally posted by @Eikosa in https://github.com/pyrogram/pyrogram/issues/1035_
